"""add name localization fields

Revision ID: 456d2c37a891
Revises: 1a9d4c7e8b10
Create Date: 2026-03-01 09:40:56.327483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '456d2c37a891'
down_revision: Union[str, Sequence[str], None] = '1a9d4c7e8b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'script_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chapters', 'world_model_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'source_language',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'continuity_status',
               existing_type=postgresql.ENUM('unbound', 'candidate', 'locked', 'drifted', name='entitycontinuitystatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'drift_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'updated_by_ai',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'version',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('entity_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_em_deleted'), table_name='entity_mappings')
    op.drop_index(op.f('ix_em_novel'), table_name='entity_mappings')
    op.drop_index(op.f('ix_em_project_id'), table_name='entity_mappings')
    op.drop_index(op.f('ix_em_status'), table_name='entity_mappings')
    op.drop_index(op.f('ix_em_tenant_id'), table_name='entity_mappings')
    op.create_index(op.f('ix_entity_mappings_correlation_id'), 'entity_mappings', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_entity_mappings_created_at'), 'entity_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_entity_mappings_deleted_at'), 'entity_mappings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_entity_mappings_error_code'), 'entity_mappings', ['error_code'], unique=False)
    op.create_index(op.f('ix_entity_mappings_idempotency_key'), 'entity_mappings', ['idempotency_key'], unique=False)
    op.create_index('ix_entity_mappings_novel', 'entity_mappings', ['novel_id'], unique=False)
    op.create_index(op.f('ix_entity_mappings_project_id'), 'entity_mappings', ['project_id'], unique=False)
    op.create_index('ix_entity_mappings_status', 'entity_mappings', ['continuity_status'], unique=False)
    op.create_index(op.f('ix_entity_mappings_tenant_id'), 'entity_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_entity_mappings_trace_id'), 'entity_mappings', ['trace_id'], unique=False)
    op.alter_column('skill_runs', 'status',
               existing_type=postgresql.ENUM('queued', 'running', 'succeeded', 'failed', name='skillrunstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_runs', 'version',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('skill_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_skill_runs_skill_id'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_status'), table_name='skill_runs')
    op.create_index(op.f('ix_skill_runs_correlation_id'), 'skill_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_created_at'), 'skill_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_runs_error_code'), 'skill_runs', ['error_code'], unique=False)
    op.create_index(op.f('ix_skill_runs_idempotency_key'), 'skill_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_skill_runs_project_id'), 'skill_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_skill_runs_trace_id'), 'skill_runs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_runs_trace_id'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_project_id'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_idempotency_key'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_error_code'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_created_at'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_correlation_id'), table_name='skill_runs')
    op.create_index(op.f('ix_skill_runs_status'), 'skill_runs', ['status'], unique=False)
    op.create_index(op.f('ix_skill_runs_skill_id'), 'skill_runs', ['skill_id'], unique=False)
    op.alter_column('skill_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('skill_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('skill_runs', 'version',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'v1'::character varying"),
               existing_nullable=False)
    op.alter_column('skill_runs', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('skill_runs', 'status',
               existing_type=postgresql.ENUM('queued', 'running', 'succeeded', 'failed', name='skillrunstatus'),
               server_default=sa.text("'queued'::skillrunstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_entity_mappings_trace_id'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_tenant_id'), table_name='entity_mappings')
    op.drop_index('ix_entity_mappings_status', table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_project_id'), table_name='entity_mappings')
    op.drop_index('ix_entity_mappings_novel', table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_idempotency_key'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_error_code'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_deleted_at'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_created_at'), table_name='entity_mappings')
    op.drop_index(op.f('ix_entity_mappings_correlation_id'), table_name='entity_mappings')
    op.create_index(op.f('ix_em_tenant_id'), 'entity_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_em_status'), 'entity_mappings', ['continuity_status'], unique=False)
    op.create_index(op.f('ix_em_project_id'), 'entity_mappings', ['project_id'], unique=False)
    op.create_index(op.f('ix_em_novel'), 'entity_mappings', ['novel_id'], unique=False)
    op.create_index(op.f('ix_em_deleted'), 'entity_mappings', ['deleted_at'], unique=False)
    op.alter_column('entity_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'version',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'v1'::character varying"),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'updated_by_ai',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'drift_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'continuity_status',
               existing_type=postgresql.ENUM('unbound', 'candidate', 'locked', 'drifted', name='entitycontinuitystatus'),
               server_default=sa.text("'unbound'::entitycontinuitystatus"),
               existing_nullable=False)
    op.alter_column('entity_mappings', 'source_language',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'zh-CN'::character varying"),
               existing_nullable=False)
    op.alter_column('chapters', 'world_model_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('chapters', 'script_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
