"""entity appellations

Revision ID: 01cb81a9150e
Revises: 99e952ab9417
Create Date: 2026-08-28 12:22:04.904826
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '01cb81a9150e'
down_revision = '99e952ab9417'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_appellations',
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('transform_id', sa.String(length=32), nullable=True),
    sa.Column('source_surface', sa.String(length=128), nullable=False),
    sa.Column('register', sa.Enum('formal_full', 'formal_title', 'respectful', 'intimate', 'diminutive', 'kinship', 'epithet', 'derogatory', 'pronoun_like', name='register', schema='core', inherit_schema=True), nullable=False),
    sa.Column('speaker_hint', sa.String(length=128), nullable=True),
    sa.Column('target_surface', sa.String(length=256), nullable=True),
    sa.Column('relation_note', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked', name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_entity_appellations_entity_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transform_id'], ['core.world_transforms.id'], name=op.f('fk_entity_appellations_transform_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_appellations')),
    sa.UniqueConstraint('entity_id', 'transform_id', 'source_surface', name='uq_appellation_entity_transform_surface'),
    schema='core'
    )
    op.create_index('ix_appellation_entity', 'entity_appellations', ['entity_id'], unique=False, schema='core')
    op.create_index('ix_appellation_transform', 'entity_appellations', ['transform_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_entity_appellations_created_at'), 'entity_appellations', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_entity_appellations_workspace_id'), 'entity_appellations', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_appellations_workspace_id'), table_name='entity_appellations', schema='core')
    op.drop_index(op.f('ix_entity_appellations_created_at'), table_name='entity_appellations', schema='core')
    op.drop_index('ix_appellation_transform', table_name='entity_appellations', schema='core')
    op.drop_index('ix_appellation_entity', table_name='entity_appellations', schema='core')
    op.drop_table('entity_appellations', schema='core')
    # ### end Alembic commands ###
