"""v2 core baseline 30 tables

Revision ID: 16be091fd24b
Revises: 
Create Date: 2026-08-27 00:57:17.388811
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '16be091fd24b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('kind', sa.Enum('image', 'audio', 'video', 'text', 'other', name='assetkind', schema='core', inherit_schema=True), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('generated', 'uploaded', 'external', name='assetsource', schema='core', inherit_schema=True), nullable=False),
    sa.Column('gen_task_id', sa.String(length=32), nullable=True),
    sa.Column('novel_id', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    schema='core'
    )
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False, schema='core')
    op.create_index('ix_assets_novel_kind', 'assets', ['novel_id', 'kind'], unique=False, schema='core')
    op.create_index('ix_assets_sha256', 'assets', ['sha256'], unique=False, schema='core')
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False, schema='core')
    op.create_table('capability_endpoints',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('auth_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('health_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caps_cache_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caps_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_version', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_endpoints')),
    sa.UniqueConstraint('name', name='uq_capability_endpoints_name'),
    schema='core'
    )
    op.create_index(op.f('ix_capability_endpoints_created_at'), 'capability_endpoints', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_capability_endpoints_workspace_id'), 'capability_endpoints', ['workspace_id'], unique=False, schema='core')
    op.create_table('gen_tasks',
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint_id', sa.String(length=32), nullable=True),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'submitted', 'running', 'succeeded', 'failed', 'cancelled', name='taskstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_ms', sa.Integer(), nullable=True),
    sa.Column('poll_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_kind', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('novel_id', sa.String(length=32), nullable=True),
    sa.Column('chapter_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gen_tasks')),
    sa.UniqueConstraint('idempotency_key', name='uq_gen_tasks_idem'),
    schema='core'
    )
    op.create_index(op.f('ix_gen_tasks_created_at'), 'gen_tasks', ['created_at'], unique=False, schema='core')
    op.create_index('ix_gen_tasks_novel', 'gen_tasks', ['novel_id'], unique=False, schema='core')
    op.create_index(op.f('ix_gen_tasks_poll_after'), 'gen_tasks', ['poll_after'], unique=False, schema='core')
    op.create_index('ix_gen_tasks_provider_task', 'gen_tasks', ['provider_task_id'], unique=False, schema='core')
    op.create_index('ix_gen_tasks_ref', 'gen_tasks', ['ref_kind', 'ref_id'], unique=False, schema='core')
    op.create_index('ix_gen_tasks_status_cap', 'gen_tasks', ['status', 'capability'], unique=False, schema='core')
    op.create_index(op.f('ix_gen_tasks_workspace_id'), 'gen_tasks', ['workspace_id'], unique=False, schema='core')
    op.create_table('novels',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('source_language_code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_asset_id', sa.String(length=32), nullable=True),
    sa.Column('default_target_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_world_profile_id', sa.String(length=32), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_novels')),
    schema='core'
    )
    op.create_index(op.f('ix_novels_created_at'), 'novels', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_novels_workspace_id'), 'novels', ['workspace_id'], unique=False, schema='core')
    op.create_table('prompt_templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('key', 'version', name='uq_prompt_templates_key_ver'),
    schema='core'
    )
    op.create_index(op.f('ix_prompt_templates_created_at'), 'prompt_templates', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_prompt_templates_workspace_id'), 'prompt_templates', ['workspace_id'], unique=False, schema='core')
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='uq_users_username'),
    schema='core'
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_lexicon_templates',
    sa.Column('pair_code', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('source_profile_code', sa.String(length=64), nullable=False),
    sa.Column('target_profile_code', sa.String(length=64), nullable=False),
    sa.Column('entries_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_lexicon_templates')),
    sa.UniqueConstraint('pair_code', 'version', name='uq_lexicon_tpl_pair_version'),
    schema='core'
    )
    op.create_index(op.f('ix_world_lexicon_templates_created_at'), 'world_lexicon_templates', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_world_lexicon_templates_workspace_id'), 'world_lexicon_templates', ['workspace_id'], unique=False, schema='core')
    op.create_table('capability_routes',
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('endpoint_id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['core.capability_endpoints.id'], name=op.f('fk_capability_routes_endpoint_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_routes')),
    sa.UniqueConstraint('capability', 'purpose', 'priority', name='uq_capability_routes_cap_purpose_prio'),
    schema='core'
    )
    op.create_index(op.f('ix_capability_routes_created_at'), 'capability_routes', ['created_at'], unique=False, schema='core')
    op.create_index('ix_capability_routes_lookup', 'capability_routes', ['capability', 'purpose', 'enabled'], unique=False, schema='core')
    op.create_index(op.f('ix_capability_routes_workspace_id'), 'capability_routes', ['workspace_id'], unique=False, schema='core')
    op.create_table('chapters',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('source_format', sa.Enum('plain', 'markdown', 'epub_html', name='sourceformat', schema='core', inherit_schema=True), nullable=False),
    sa.Column('ingest_meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_chapters_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('novel_id', 'order_no', name='uq_chapters_novel_order'),
    schema='core'
    )
    op.create_index(op.f('ix_chapters_created_at'), 'chapters', ['created_at'], unique=False, schema='core')
    op.create_index('ix_chapters_novel_order', 'chapters', ['novel_id', 'order_no'], unique=False, schema='core')
    op.create_index(op.f('ix_chapters_workspace_id'), 'chapters', ['workspace_id'], unique=False, schema='core')
    op.create_table('consistency_warnings',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('translation_block_id', sa.String(length=32), nullable=True),
    sa.Column('warning_type', sa.Enum('name_drift', 'new_variant', 'cross_chapter', 'glossary_missing', 'glossary_drift', name='warningtype', schema='core', inherit_schema=True), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('detected_variant', sa.String(length=256), nullable=False),
    sa.Column('expected_canonical', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='warningstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_consistency_warnings_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consistency_warnings')),
    schema='core'
    )
    op.create_index(op.f('ix_consistency_warnings_created_at'), 'consistency_warnings', ['created_at'], unique=False, schema='core')
    op.create_index('ix_consistency_warnings_scope', 'consistency_warnings', ['novel_id', 'target_language_code', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_consistency_warnings_workspace_id'), 'consistency_warnings', ['workspace_id'], unique=False, schema='core')
    op.create_table('glossary_candidates',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('source_language_code', sa.String(length=16), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('source_term', sa.String(length=256), nullable=False),
    sa.Column('suggested_target_term', sa.String(length=256), nullable=True),
    sa.Column('term_type', sa.Enum('proper_noun', 'artifact', 'creature', 'place', 'faction', 'technique', 'cultural', 'other', name='termtype', schema='core', inherit_schema=True), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', 'merged', name='candidatestatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('source_block_id', sa.String(length=32), nullable=True),
    sa.Column('normalized_term', sa.String(length=256), nullable=True),
    sa.Column('candidate_reason', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('approved_term_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_glossary_candidates_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_candidates')),
    schema='core'
    )
    op.create_index(op.f('ix_glossary_candidates_created_at'), 'glossary_candidates', ['created_at'], unique=False, schema='core')
    op.create_index('ix_glossary_candidates_scope', 'glossary_candidates', ['novel_id', 'target_language_code', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_glossary_candidates_workspace_id'), 'glossary_candidates', ['workspace_id'], unique=False, schema='core')
    op.create_table('glossary_terms',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('source_language_code', sa.String(length=16), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('source_term', sa.String(length=256), nullable=False),
    sa.Column('target_term', sa.String(length=256), nullable=False),
    sa.Column('term_type', sa.Enum('proper_noun', 'artifact', 'creature', 'place', 'faction', 'technique', 'cultural', 'other', name='termtype', schema='core', inherit_schema=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'archived', name='termstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_glossary_terms_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_terms')),
    schema='core'
    )
    op.create_index(op.f('ix_glossary_terms_created_at'), 'glossary_terms', ['created_at'], unique=False, schema='core')
    op.create_index('ix_glossary_terms_scope', 'glossary_terms', ['novel_id', 'target_language_code', 'status'], unique=False, schema='core')
    op.create_index('ix_glossary_terms_source', 'glossary_terms', ['source_term'], unique=False, schema='core')
    op.create_index(op.f('ix_glossary_terms_workspace_id'), 'glossary_terms', ['workspace_id'], unique=False, schema='core')
    op.create_table('novel_translation_settings',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('consistency_mode', sa.Enum('strict', 'balanced', 'free', name='consistencymode', schema='core', inherit_schema=True), nullable=False),
    sa.Column('translatable_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_prompt', sa.Text(), nullable=True),
    sa.Column('capability_route', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_novel_translation_settings_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_novel_translation_settings')),
    sa.UniqueConstraint('novel_id', 'target_language_code', name='uq_nts_novel_lang'),
    schema='core'
    )
    op.create_index(op.f('ix_novel_translation_settings_created_at'), 'novel_translation_settings', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_novel_translation_settings_workspace_id'), 'novel_translation_settings', ['workspace_id'], unique=False, schema='core')
    op.create_table('translation_runs',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('transform_id', sa.String(length=32), nullable=True),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='runstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_translation_runs_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_runs')),
    schema='core'
    )
    op.create_index(op.f('ix_translation_runs_created_at'), 'translation_runs', ['created_at'], unique=False, schema='core')
    op.create_index('ix_translation_runs_novel_status', 'translation_runs', ['novel_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_translation_runs_transform_id'), 'translation_runs', ['transform_id'], unique=False, schema='core')
    op.create_index(op.f('ix_translation_runs_workspace_id'), 'translation_runs', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_entities',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('character', 'location', 'prop', 'faction', 'style', name='entitykind', schema='core', inherit_schema=True), nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('localized_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('family_key', sa.String(length=64), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_entity_id', sa.String(length=32), nullable=True),
    sa.Column('voice_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('first_seen_chapter_order', sa.Integer(), nullable=True),
    sa.Column('appear_chapters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_world_entities_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_entities')),
    sa.UniqueConstraint('novel_id', 'canonical_key', name='uq_world_entities_novel_key'),
    schema='core'
    )
    op.create_index(op.f('ix_world_entities_created_at'), 'world_entities', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_world_entities_family_key'), 'world_entities', ['family_key'], unique=False, schema='core')
    op.create_index('ix_world_entities_novel_kind', 'world_entities', ['novel_id', 'kind'], unique=False, schema='core')
    op.create_index(op.f('ix_world_entities_workspace_id'), 'world_entities', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_profiles',
    sa.Column('novel_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('source', 'target', 'both', name='profilerole', schema='core', inherit_schema=True), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('axes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kb_collection_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='profilestatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_world_profiles_novel_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['core.world_profiles.id'], name=op.f('fk_world_profiles_parent_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_profiles')),
    sa.UniqueConstraint('code', 'version', name='uq_world_profiles_code_version'),
    schema='core'
    )
    op.create_index(op.f('ix_world_profiles_code'), 'world_profiles', ['code'], unique=False, schema='core')
    op.create_index(op.f('ix_world_profiles_created_at'), 'world_profiles', ['created_at'], unique=False, schema='core')
    op.create_index('ix_world_profiles_novel_status', 'world_profiles', ['novel_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_world_profiles_workspace_id'), 'world_profiles', ['workspace_id'], unique=False, schema='core')
    op.create_table('entity_chapter_states',
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('chapter_order_from', sa.Integer(), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_prompt_override', sa.Text(), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_entity_chapter_states_entity_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_chapter_states')),
    schema='core'
    )
    op.create_index(op.f('ix_entity_chapter_states_created_at'), 'entity_chapter_states', ['created_at'], unique=False, schema='core')
    op.create_index('ix_entity_chapter_states_lookup', 'entity_chapter_states', ['entity_id', 'chapter_order_from'], unique=False, schema='core')
    op.create_index(op.f('ix_entity_chapter_states_workspace_id'), 'entity_chapter_states', ['workspace_id'], unique=False, schema='core')
    op.create_table('entity_world_visual',
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('world_profile_id', sa.String(length=32), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('costume_note', sa.Text(), nullable=True),
    sa.Column('prop_note', sa.Text(), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'approved', 'locked', name='reviewstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_entity_world_visual_entity_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_profile_id'], ['core.world_profiles.id'], name=op.f('fk_entity_world_visual_world_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_world_visual')),
    sa.UniqueConstraint('entity_id', 'world_profile_id', name='uq_ewv_entity_profile'),
    schema='core'
    )
    op.create_index(op.f('ix_entity_world_visual_created_at'), 'entity_world_visual', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_entity_world_visual_workspace_id'), 'entity_world_visual', ['workspace_id'], unique=False, schema='core')
    op.create_table('script_docs',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='docstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('language_source', sa.String(length=16), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('generator_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_script_docs_chapter_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_docs')),
    sa.UniqueConstraint('chapter_id', 'version', name='uq_script_docs_chapter_version'),
    schema='core'
    )
    op.create_index('ix_script_docs_chapter_status', 'script_docs', ['chapter_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_script_docs_created_at'), 'script_docs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_script_docs_input_fingerprint'), 'script_docs', ['input_fingerprint'], unique=False, schema='core')
    op.create_index(op.f('ix_script_docs_workspace_id'), 'script_docs', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_transforms',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('source_profile_id', sa.String(length=32), nullable=False),
    sa.Column('target_profile_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='transformstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_world_transforms_novel_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_profile_id'], ['core.world_profiles.id'], name=op.f('fk_world_transforms_source_profile_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_profile_id'], ['core.world_profiles.id'], name=op.f('fk_world_transforms_target_profile_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_transforms')),
    sa.UniqueConstraint('novel_id', 'target_language_code', 'version', name='uq_wt_novel_lang_version'),
    schema='core'
    )
    op.create_index(op.f('ix_world_transforms_created_at'), 'world_transforms', ['created_at'], unique=False, schema='core')
    op.create_index('ix_world_transforms_novel_status', 'world_transforms', ['novel_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_world_transforms_workspace_id'), 'world_transforms', ['workspace_id'], unique=False, schema='core')
    op.create_table('entity_world_names',
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('transform_id', sa.String(length=32), nullable=False),
    sa.Column('target_name', sa.String(length=256), nullable=False),
    sa.Column('target_reading', sa.String(length=256), nullable=True),
    sa.Column('family_key', sa.String(length=64), nullable=True),
    sa.Column('family_surname', sa.String(length=128), nullable=True),
    sa.Column('naming_policy', sa.Enum('transliteration', 'literal', 'cultural_equivalent', 'hybrid', name='namingpolicy', schema='core', inherit_schema=True), nullable=False),
    sa.Column('candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'approved', 'locked', name='reviewstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_entity_world_names_entity_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transform_id'], ['core.world_transforms.id'], name=op.f('fk_entity_world_names_transform_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_world_names')),
    sa.UniqueConstraint('entity_id', 'transform_id', name='uq_ewn_entity_transform'),
    schema='core'
    )
    op.create_index(op.f('ix_entity_world_names_created_at'), 'entity_world_names', ['created_at'], unique=False, schema='core')
    op.create_index('ix_entity_world_names_family', 'entity_world_names', ['transform_id', 'family_key'], unique=False, schema='core')
    op.create_index('ix_entity_world_names_status', 'entity_world_names', ['transform_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_entity_world_names_workspace_id'), 'entity_world_names', ['workspace_id'], unique=False, schema='core')
    op.create_table('scenes',
    sa.Column('script_doc_id', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('time_of_day', sa.String(length=64), nullable=True),
    sa.Column('location_entity_id', sa.String(length=32), nullable=True),
    sa.Column('location_text', sa.String(length=256), nullable=True),
    sa.Column('weather', sa.String(length=64), nullable=True),
    sa.Column('mood', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('bg_asset_id', sa.String(length=32), nullable=True),
    sa.Column('bgm_asset_id', sa.String(length=32), nullable=True),
    sa.Column('ambience_asset_id', sa.String(length=32), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_doc_id'], ['core.script_docs.id'], name=op.f('fk_scenes_script_doc_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes')),
    schema='core'
    )
    op.create_index(op.f('ix_scenes_created_at'), 'scenes', ['created_at'], unique=False, schema='core')
    op.create_index('ix_scenes_doc_order', 'scenes', ['script_doc_id', 'order_no'], unique=False, schema='core')
    op.create_index(op.f('ix_scenes_workspace_id'), 'scenes', ['workspace_id'], unique=False, schema='core')
    op.create_table('shot_plans',
    sa.Column('script_doc_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='docstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=True),
    sa.Column('transform_id', sa.String(length=32), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_doc_id'], ['core.script_docs.id'], name=op.f('fk_shot_plans_script_doc_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_plans')),
    sa.UniqueConstraint('script_doc_id', 'version', name='uq_shot_plans_doc_version'),
    schema='core'
    )
    op.create_index(op.f('ix_shot_plans_created_at'), 'shot_plans', ['created_at'], unique=False, schema='core')
    op.create_index('ix_shot_plans_doc_status', 'shot_plans', ['script_doc_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_plans_transform_id'), 'shot_plans', ['transform_id'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_plans_workspace_id'), 'shot_plans', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_lexicon',
    sa.Column('transform_id', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('place', 'office', 'title', 'honorific', 'garment', 'food', 'currency', 'weapon', 'vehicle', 'architecture', 'custom', 'ritual', 'measure', 'other', name='lexiconcategory', schema='core', inherit_schema=True), nullable=False),
    sa.Column('source_term', sa.String(length=256), nullable=False),
    sa.Column('source_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_term', sa.String(length=256), nullable=False),
    sa.Column('target_reading', sa.String(length=256), nullable=True),
    sa.Column('forbidden_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'approved', 'locked', name='reviewstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('template', 'mined', 'rag', 'manual', name='lexiconsource', schema='core', inherit_schema=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transform_id'], ['core.world_transforms.id'], name=op.f('fk_world_lexicon_transform_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_lexicon')),
    sa.UniqueConstraint('transform_id', 'source_term', name='uq_lexicon_transform_source'),
    schema='core'
    )
    op.create_index('ix_world_lexicon_canonical', 'world_lexicon', ['transform_id', 'canonical_key'], unique=False, schema='core')
    op.create_index('ix_world_lexicon_category', 'world_lexicon', ['transform_id', 'category'], unique=False, schema='core')
    op.create_index(op.f('ix_world_lexicon_created_at'), 'world_lexicon', ['created_at'], unique=False, schema='core')
    op.create_index('ix_world_lexicon_status', 'world_lexicon', ['transform_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_world_lexicon_workspace_id'), 'world_lexicon', ['workspace_id'], unique=False, schema='core')
    op.create_table('world_violations',
    sa.Column('transform_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('name_drift', 'name_family_conflict', 'lexicon_miss', 'forbidden_token', 'register_conflict', 'era_conflict', 'genre_conflict', 'costume_conflict', 'prop_region_conflict', 'architecture_conflict', 'signage_conflict', 'social_norm_conflict', name='violationkind', schema='core', inherit_schema=True), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity', schema='core', inherit_schema=True), nullable=False),
    sa.Column('scope', sa.Enum('block', 'shot', 'entity', 'scene', name='violationscope', schema='core', inherit_schema=True), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('detected', sa.String(length=512), nullable=False),
    sa.Column('expected', sa.String(length=512), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='violationstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transform_id'], ['core.world_transforms.id'], name=op.f('fk_world_violations_transform_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_violations')),
    schema='core'
    )
    op.create_index(op.f('ix_world_violations_created_at'), 'world_violations', ['created_at'], unique=False, schema='core')
    op.create_index('ix_world_violations_ref', 'world_violations', ['scope', 'ref_id'], unique=False, schema='core')
    op.create_index('ix_world_violations_scope', 'world_violations', ['transform_id', 'status', 'severity'], unique=False, schema='core')
    op.create_index(op.f('ix_world_violations_workspace_id'), 'world_violations', ['workspace_id'], unique=False, schema='core')
    op.create_table('script_blocks',
    sa.Column('script_doc_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('narration', 'dialogue', 'action', 'signage', 'title', 'inner_monolog', 'heading', 'scene_break', name='blocktype', schema='core', inherit_schema=True), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('speaker_tag', sa.String(length=128), nullable=True),
    sa.Column('speaker_entity_id', sa.String(length=32), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['core.scenes.id'], name=op.f('fk_script_blocks_scene_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['script_doc_id'], ['core.script_docs.id'], name=op.f('fk_script_blocks_script_doc_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_blocks')),
    schema='core'
    )
    op.create_index(op.f('ix_script_blocks_created_at'), 'script_blocks', ['created_at'], unique=False, schema='core')
    op.create_index('ix_script_blocks_doc_seq', 'script_blocks', ['script_doc_id', 'seq_no'], unique=False, schema='core')
    op.create_index('ix_script_blocks_scene', 'script_blocks', ['scene_id'], unique=False, schema='core')
    op.create_index(op.f('ix_script_blocks_speaker_entity_id'), 'script_blocks', ['speaker_entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_script_blocks_workspace_id'), 'script_blocks', ['workspace_id'], unique=False, schema='core')
    op.create_table('shots',
    sa.Column('shot_plan_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('block_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('camera_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'approved', 'failed', 'skipped', name='specstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('video_asset_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['core.scenes.id'], name=op.f('fk_shots_scene_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_plan_id'], ['core.shot_plans.id'], name=op.f('fk_shots_shot_plan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots')),
    schema='core'
    )
    op.create_index(op.f('ix_shots_created_at'), 'shots', ['created_at'], unique=False, schema='core')
    op.create_index('ix_shots_plan_order', 'shots', ['shot_plan_id', 'order_no'], unique=False, schema='core')
    op.create_index('ix_shots_scene', 'shots', ['scene_id'], unique=False, schema='core')
    op.create_index(op.f('ix_shots_spec_fingerprint'), 'shots', ['spec_fingerprint'], unique=False, schema='core')
    op.create_index(op.f('ix_shots_workspace_id'), 'shots', ['workspace_id'], unique=False, schema='core')
    op.create_table('audio_specs',
    sa.Column('shot_id', sa.String(length=32), nullable=True),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.Enum('dialogue', 'narration', 'sfx', 'bgm', 'ambience', name='audiokind', schema='core', inherit_schema=True), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamps_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gen_task_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'approved', 'failed', 'skipped', name='specstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['core.scenes.id'], name=op.f('fk_audio_specs_scene_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_audio_specs_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_specs')),
    schema='core'
    )
    op.create_index(op.f('ix_audio_specs_created_at'), 'audio_specs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_audio_specs_gen_task_id'), 'audio_specs', ['gen_task_id'], unique=False, schema='core')
    op.create_index('ix_audio_specs_scene', 'audio_specs', ['scene_id'], unique=False, schema='core')
    op.create_index('ix_audio_specs_shot', 'audio_specs', ['shot_id'], unique=False, schema='core')
    op.create_index('ix_audio_specs_status', 'audio_specs', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_audio_specs_workspace_id'), 'audio_specs', ['workspace_id'], unique=False, schema='core')
    op.create_table('frame_specs',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('first', 'last', name='framerole', schema='core', inherit_schema=True), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('entity_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('derive_from_first', sa.Boolean(), nullable=False),
    sa.Column('derive_instruction', sa.Text(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('gen_task_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'approved', 'failed', 'skipped', name='specstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_frame_specs_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frame_specs')),
    sa.UniqueConstraint('shot_id', 'role', name='uq_frame_specs_shot_role'),
    schema='core'
    )
    op.create_index(op.f('ix_frame_specs_created_at'), 'frame_specs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_frame_specs_gen_task_id'), 'frame_specs', ['gen_task_id'], unique=False, schema='core')
    op.create_index('ix_frame_specs_status', 'frame_specs', ['status'], unique=False, schema='core')
    op.create_index(op.f('ix_frame_specs_workspace_id'), 'frame_specs', ['workspace_id'], unique=False, schema='core')
    op.create_table('translation_blocks',
    sa.Column('script_block_id', sa.String(length=32), nullable=False),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'locked', name='translationblockstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('translation_notes', sa.Text(), nullable=True),
    sa.Column('glossary_hits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lexicon_hits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_block_id'], ['core.script_blocks.id'], name=op.f('fk_translation_blocks_script_block_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_blocks')),
    sa.UniqueConstraint('script_block_id', 'target_language_code', name='uq_tb_block_lang'),
    schema='core'
    )
    op.create_index(op.f('ix_translation_blocks_created_at'), 'translation_blocks', ['created_at'], unique=False, schema='core')
    op.create_index('ix_translation_blocks_lang_status', 'translation_blocks', ['target_language_code', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_translation_blocks_run_id'), 'translation_blocks', ['run_id'], unique=False, schema='core')
    op.create_index(op.f('ix_translation_blocks_workspace_id'), 'translation_blocks', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_blocks_workspace_id'), table_name='translation_blocks', schema='core')
    op.drop_index(op.f('ix_translation_blocks_run_id'), table_name='translation_blocks', schema='core')
    op.drop_index('ix_translation_blocks_lang_status', table_name='translation_blocks', schema='core')
    op.drop_index(op.f('ix_translation_blocks_created_at'), table_name='translation_blocks', schema='core')
    op.drop_table('translation_blocks', schema='core')
    op.drop_index(op.f('ix_frame_specs_workspace_id'), table_name='frame_specs', schema='core')
    op.drop_index('ix_frame_specs_status', table_name='frame_specs', schema='core')
    op.drop_index(op.f('ix_frame_specs_gen_task_id'), table_name='frame_specs', schema='core')
    op.drop_index(op.f('ix_frame_specs_created_at'), table_name='frame_specs', schema='core')
    op.drop_table('frame_specs', schema='core')
    op.drop_index(op.f('ix_audio_specs_workspace_id'), table_name='audio_specs', schema='core')
    op.drop_index('ix_audio_specs_status', table_name='audio_specs', schema='core')
    op.drop_index('ix_audio_specs_shot', table_name='audio_specs', schema='core')
    op.drop_index('ix_audio_specs_scene', table_name='audio_specs', schema='core')
    op.drop_index(op.f('ix_audio_specs_gen_task_id'), table_name='audio_specs', schema='core')
    op.drop_index(op.f('ix_audio_specs_created_at'), table_name='audio_specs', schema='core')
    op.drop_table('audio_specs', schema='core')
    op.drop_index(op.f('ix_shots_workspace_id'), table_name='shots', schema='core')
    op.drop_index(op.f('ix_shots_spec_fingerprint'), table_name='shots', schema='core')
    op.drop_index('ix_shots_scene', table_name='shots', schema='core')
    op.drop_index('ix_shots_plan_order', table_name='shots', schema='core')
    op.drop_index(op.f('ix_shots_created_at'), table_name='shots', schema='core')
    op.drop_table('shots', schema='core')
    op.drop_index(op.f('ix_script_blocks_workspace_id'), table_name='script_blocks', schema='core')
    op.drop_index(op.f('ix_script_blocks_speaker_entity_id'), table_name='script_blocks', schema='core')
    op.drop_index('ix_script_blocks_scene', table_name='script_blocks', schema='core')
    op.drop_index('ix_script_blocks_doc_seq', table_name='script_blocks', schema='core')
    op.drop_index(op.f('ix_script_blocks_created_at'), table_name='script_blocks', schema='core')
    op.drop_table('script_blocks', schema='core')
    op.drop_index(op.f('ix_world_violations_workspace_id'), table_name='world_violations', schema='core')
    op.drop_index('ix_world_violations_scope', table_name='world_violations', schema='core')
    op.drop_index('ix_world_violations_ref', table_name='world_violations', schema='core')
    op.drop_index(op.f('ix_world_violations_created_at'), table_name='world_violations', schema='core')
    op.drop_table('world_violations', schema='core')
    op.drop_index(op.f('ix_world_lexicon_workspace_id'), table_name='world_lexicon', schema='core')
    op.drop_index('ix_world_lexicon_status', table_name='world_lexicon', schema='core')
    op.drop_index(op.f('ix_world_lexicon_created_at'), table_name='world_lexicon', schema='core')
    op.drop_index('ix_world_lexicon_category', table_name='world_lexicon', schema='core')
    op.drop_index('ix_world_lexicon_canonical', table_name='world_lexicon', schema='core')
    op.drop_table('world_lexicon', schema='core')
    op.drop_index(op.f('ix_shot_plans_workspace_id'), table_name='shot_plans', schema='core')
    op.drop_index(op.f('ix_shot_plans_transform_id'), table_name='shot_plans', schema='core')
    op.drop_index('ix_shot_plans_doc_status', table_name='shot_plans', schema='core')
    op.drop_index(op.f('ix_shot_plans_created_at'), table_name='shot_plans', schema='core')
    op.drop_table('shot_plans', schema='core')
    op.drop_index(op.f('ix_scenes_workspace_id'), table_name='scenes', schema='core')
    op.drop_index('ix_scenes_doc_order', table_name='scenes', schema='core')
    op.drop_index(op.f('ix_scenes_created_at'), table_name='scenes', schema='core')
    op.drop_table('scenes', schema='core')
    op.drop_index(op.f('ix_entity_world_names_workspace_id'), table_name='entity_world_names', schema='core')
    op.drop_index('ix_entity_world_names_status', table_name='entity_world_names', schema='core')
    op.drop_index('ix_entity_world_names_family', table_name='entity_world_names', schema='core')
    op.drop_index(op.f('ix_entity_world_names_created_at'), table_name='entity_world_names', schema='core')
    op.drop_table('entity_world_names', schema='core')
    op.drop_index(op.f('ix_world_transforms_workspace_id'), table_name='world_transforms', schema='core')
    op.drop_index('ix_world_transforms_novel_status', table_name='world_transforms', schema='core')
    op.drop_index(op.f('ix_world_transforms_created_at'), table_name='world_transforms', schema='core')
    op.drop_table('world_transforms', schema='core')
    op.drop_index(op.f('ix_script_docs_workspace_id'), table_name='script_docs', schema='core')
    op.drop_index(op.f('ix_script_docs_input_fingerprint'), table_name='script_docs', schema='core')
    op.drop_index(op.f('ix_script_docs_created_at'), table_name='script_docs', schema='core')
    op.drop_index('ix_script_docs_chapter_status', table_name='script_docs', schema='core')
    op.drop_table('script_docs', schema='core')
    op.drop_index(op.f('ix_entity_world_visual_workspace_id'), table_name='entity_world_visual', schema='core')
    op.drop_index(op.f('ix_entity_world_visual_created_at'), table_name='entity_world_visual', schema='core')
    op.drop_table('entity_world_visual', schema='core')
    op.drop_index(op.f('ix_entity_chapter_states_workspace_id'), table_name='entity_chapter_states', schema='core')
    op.drop_index('ix_entity_chapter_states_lookup', table_name='entity_chapter_states', schema='core')
    op.drop_index(op.f('ix_entity_chapter_states_created_at'), table_name='entity_chapter_states', schema='core')
    op.drop_table('entity_chapter_states', schema='core')
    op.drop_index(op.f('ix_world_profiles_workspace_id'), table_name='world_profiles', schema='core')
    op.drop_index('ix_world_profiles_novel_status', table_name='world_profiles', schema='core')
    op.drop_index(op.f('ix_world_profiles_created_at'), table_name='world_profiles', schema='core')
    op.drop_index(op.f('ix_world_profiles_code'), table_name='world_profiles', schema='core')
    op.drop_table('world_profiles', schema='core')
    op.drop_index(op.f('ix_world_entities_workspace_id'), table_name='world_entities', schema='core')
    op.drop_index('ix_world_entities_novel_kind', table_name='world_entities', schema='core')
    op.drop_index(op.f('ix_world_entities_family_key'), table_name='world_entities', schema='core')
    op.drop_index(op.f('ix_world_entities_created_at'), table_name='world_entities', schema='core')
    op.drop_table('world_entities', schema='core')
    op.drop_index(op.f('ix_translation_runs_workspace_id'), table_name='translation_runs', schema='core')
    op.drop_index(op.f('ix_translation_runs_transform_id'), table_name='translation_runs', schema='core')
    op.drop_index('ix_translation_runs_novel_status', table_name='translation_runs', schema='core')
    op.drop_index(op.f('ix_translation_runs_created_at'), table_name='translation_runs', schema='core')
    op.drop_table('translation_runs', schema='core')
    op.drop_index(op.f('ix_novel_translation_settings_workspace_id'), table_name='novel_translation_settings', schema='core')
    op.drop_index(op.f('ix_novel_translation_settings_created_at'), table_name='novel_translation_settings', schema='core')
    op.drop_table('novel_translation_settings', schema='core')
    op.drop_index(op.f('ix_glossary_terms_workspace_id'), table_name='glossary_terms', schema='core')
    op.drop_index('ix_glossary_terms_source', table_name='glossary_terms', schema='core')
    op.drop_index('ix_glossary_terms_scope', table_name='glossary_terms', schema='core')
    op.drop_index(op.f('ix_glossary_terms_created_at'), table_name='glossary_terms', schema='core')
    op.drop_table('glossary_terms', schema='core')
    op.drop_index(op.f('ix_glossary_candidates_workspace_id'), table_name='glossary_candidates', schema='core')
    op.drop_index('ix_glossary_candidates_scope', table_name='glossary_candidates', schema='core')
    op.drop_index(op.f('ix_glossary_candidates_created_at'), table_name='glossary_candidates', schema='core')
    op.drop_table('glossary_candidates', schema='core')
    op.drop_index(op.f('ix_consistency_warnings_workspace_id'), table_name='consistency_warnings', schema='core')
    op.drop_index('ix_consistency_warnings_scope', table_name='consistency_warnings', schema='core')
    op.drop_index(op.f('ix_consistency_warnings_created_at'), table_name='consistency_warnings', schema='core')
    op.drop_table('consistency_warnings', schema='core')
    op.drop_index(op.f('ix_chapters_workspace_id'), table_name='chapters', schema='core')
    op.drop_index('ix_chapters_novel_order', table_name='chapters', schema='core')
    op.drop_index(op.f('ix_chapters_created_at'), table_name='chapters', schema='core')
    op.drop_table('chapters', schema='core')
    op.drop_index(op.f('ix_capability_routes_workspace_id'), table_name='capability_routes', schema='core')
    op.drop_index('ix_capability_routes_lookup', table_name='capability_routes', schema='core')
    op.drop_index(op.f('ix_capability_routes_created_at'), table_name='capability_routes', schema='core')
    op.drop_table('capability_routes', schema='core')
    op.drop_index(op.f('ix_world_lexicon_templates_workspace_id'), table_name='world_lexicon_templates', schema='core')
    op.drop_index(op.f('ix_world_lexicon_templates_created_at'), table_name='world_lexicon_templates', schema='core')
    op.drop_table('world_lexicon_templates', schema='core')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users', schema='core')
    op.drop_index(op.f('ix_users_created_at'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index(op.f('ix_prompt_templates_workspace_id'), table_name='prompt_templates', schema='core')
    op.drop_index(op.f('ix_prompt_templates_created_at'), table_name='prompt_templates', schema='core')
    op.drop_table('prompt_templates', schema='core')
    op.drop_index(op.f('ix_novels_workspace_id'), table_name='novels', schema='core')
    op.drop_index(op.f('ix_novels_created_at'), table_name='novels', schema='core')
    op.drop_table('novels', schema='core')
    op.drop_index(op.f('ix_gen_tasks_workspace_id'), table_name='gen_tasks', schema='core')
    op.drop_index('ix_gen_tasks_status_cap', table_name='gen_tasks', schema='core')
    op.drop_index('ix_gen_tasks_ref', table_name='gen_tasks', schema='core')
    op.drop_index('ix_gen_tasks_provider_task', table_name='gen_tasks', schema='core')
    op.drop_index(op.f('ix_gen_tasks_poll_after'), table_name='gen_tasks', schema='core')
    op.drop_index('ix_gen_tasks_novel', table_name='gen_tasks', schema='core')
    op.drop_index(op.f('ix_gen_tasks_created_at'), table_name='gen_tasks', schema='core')
    op.drop_table('gen_tasks', schema='core')
    op.drop_index(op.f('ix_capability_endpoints_workspace_id'), table_name='capability_endpoints', schema='core')
    op.drop_index(op.f('ix_capability_endpoints_created_at'), table_name='capability_endpoints', schema='core')
    op.drop_table('capability_endpoints', schema='core')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets', schema='core')
    op.drop_index('ix_assets_sha256', table_name='assets', schema='core')
    op.drop_index('ix_assets_novel_kind', table_name='assets', schema='core')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets', schema='core')
    op.drop_table('assets', schema='core')
    # ### end Alembic commands ###
