"""shot plan director and shot size

Revision ID: 1e948975c724
Revises: 2aafef72914a
Create Date: 2026-08-27 15:18:48.034236
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1e948975c724'
down_revision = '2aafef72914a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shot_plans', sa.Column('director_profile_id', sa.String(length=32), nullable=True), schema='core')
    op.create_index(op.f('ix_shot_plans_director_profile_id'), 'shot_plans', ['director_profile_id'], unique=False, schema='core')
    op.add_column('shots', sa.Column('shot_size', sa.String(length=8), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shots', 'shot_size', schema='core')
    op.drop_index(op.f('ix_shot_plans_director_profile_id'), table_name='shot_plans', schema='core')
    op.drop_column('shot_plans', 'director_profile_id', schema='core')
    # ### end Alembic commands ###
