"""base asset pack and director profiles

Revision ID: 2aafef72914a
Revises: 16be091fd24b
Create Date: 2026-08-27 14:41:12.653223
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '2aafef72914a'
down_revision = '16be091fd24b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('novel_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('camera_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('editing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('composition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lighting_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kb_collection_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_director_profiles_novel_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['core.director_profiles.id'], name=op.f('fk_director_profiles_parent_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_director_profiles')),
    sa.UniqueConstraint('code', 'version', name='uq_director_profiles_code_version'),
    schema='core'
    )
    op.create_index(op.f('ix_director_profiles_code'), 'director_profiles', ['code'], unique=False, schema='core')
    op.create_index(op.f('ix_director_profiles_created_at'), 'director_profiles', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_director_profiles_workspace_id'), 'director_profiles', ['workspace_id'], unique=False, schema='core')
    op.create_table('asset_specs',
    sa.Column('novel_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('costume', 'prop', 'location', 'expression', 'action', 'ambience', 'style', 'creature', name='assetkindspec', schema='core', inherit_schema=True), nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_chapter_order', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('mined', 'llm', 'template', 'manual', name='assetorigin', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_asset_specs_entity_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_asset_specs_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_specs')),
    sa.UniqueConstraint('novel_id', 'canonical_key', name='uq_asset_specs_novel_key'),
    schema='core'
    )
    op.create_index(op.f('ix_asset_specs_created_at'), 'asset_specs', ['created_at'], unique=False, schema='core')
    op.create_index('ix_asset_specs_entity', 'asset_specs', ['entity_id'], unique=False, schema='core')
    op.create_index('ix_asset_specs_novel_kind', 'asset_specs', ['novel_id', 'kind'], unique=False, schema='core')
    op.create_index(op.f('ix_asset_specs_workspace_id'), 'asset_specs', ['workspace_id'], unique=False, schema='core')
    op.create_table('asset_variants',
    sa.Column('asset_spec_id', sa.String(length=32), nullable=False),
    sa.Column('world_profile_id', sa.String(length=32), nullable=False),
    sa.Column('target_name', sa.String(length=256), nullable=False),
    sa.Column('target_reading', sa.String(length=256), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # reviewstatus 已由 world_lexicon 等表创建，复用而非重建
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked',
              name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('mined', 'llm', 'template', 'manual', name='assetorigin', schema='core', inherit_schema=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_spec_id'], ['core.asset_specs.id'], name=op.f('fk_asset_variants_asset_spec_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_profile_id'], ['core.world_profiles.id'], name=op.f('fk_asset_variants_world_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_variants')),
    sa.UniqueConstraint('asset_spec_id', 'world_profile_id', name='uq_asset_variants_spec_profile'),
    schema='core'
    )
    op.create_index(op.f('ix_asset_variants_created_at'), 'asset_variants', ['created_at'], unique=False, schema='core')
    op.create_index('ix_asset_variants_profile_status', 'asset_variants', ['world_profile_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_asset_variants_workspace_id'), 'asset_variants', ['workspace_id'], unique=False, schema='core')
    op.create_table('shot_asset_bindings',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('binding_role', sa.String(length=32), nullable=False),
    sa.Column('asset_variant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_override_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_shot_asset_bindings_entity_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_shot_asset_bindings_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_asset_bindings')),
    schema='core'
    )
    op.create_index(op.f('ix_shot_asset_bindings_created_at'), 'shot_asset_bindings', ['created_at'], unique=False, schema='core')
    op.create_index('ix_shot_asset_bindings_entity', 'shot_asset_bindings', ['entity_id'], unique=False, schema='core')
    op.create_index('ix_shot_asset_bindings_shot', 'shot_asset_bindings', ['shot_id'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_asset_bindings_workspace_id'), 'shot_asset_bindings', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_asset_bindings_workspace_id'), table_name='shot_asset_bindings', schema='core')
    op.drop_index('ix_shot_asset_bindings_shot', table_name='shot_asset_bindings', schema='core')
    op.drop_index('ix_shot_asset_bindings_entity', table_name='shot_asset_bindings', schema='core')
    op.drop_index(op.f('ix_shot_asset_bindings_created_at'), table_name='shot_asset_bindings', schema='core')
    op.drop_table('shot_asset_bindings', schema='core')
    op.drop_index(op.f('ix_asset_variants_workspace_id'), table_name='asset_variants', schema='core')
    op.drop_index('ix_asset_variants_profile_status', table_name='asset_variants', schema='core')
    op.drop_index(op.f('ix_asset_variants_created_at'), table_name='asset_variants', schema='core')
    op.drop_table('asset_variants', schema='core')
    op.drop_index(op.f('ix_asset_specs_workspace_id'), table_name='asset_specs', schema='core')
    op.drop_index('ix_asset_specs_novel_kind', table_name='asset_specs', schema='core')
    op.drop_index('ix_asset_specs_entity', table_name='asset_specs', schema='core')
    op.drop_index(op.f('ix_asset_specs_created_at'), table_name='asset_specs', schema='core')
    op.drop_table('asset_specs', schema='core')
    op.drop_index(op.f('ix_director_profiles_workspace_id'), table_name='director_profiles', schema='core')
    op.drop_index(op.f('ix_director_profiles_created_at'), table_name='director_profiles', schema='core')
    op.drop_index(op.f('ix_director_profiles_code'), table_name='director_profiles', schema='core')
    op.drop_table('director_profiles', schema='core')
    # ### end Alembic commands ###
