"""backcheck contradictions

Revision ID: 4a73d0dc50ee
Revises: 67c59188b3c6
Create Date: 2026-08-28 19:47:11.073112
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4a73d0dc50ee'
down_revision = '67c59188b3c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 改名而非重建：旧数据里的 added_content 多半是误报
    # （模型没有原文可比，只能拿骨架当原文，于是每个细节都被报成新增），
    # 但保留它们仍有价值 —— 可以拿来验证新判据是不是真的更准。
    op.alter_column('back_translation_checks', 'added_content',
                    new_column_name='contradictions', schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('back_translation_checks', 'contradictions',
                    new_column_name='added_content', schema='core')
    # ### end Alembic commands ###
