"""chkA

Revision ID: 4c4629934230
Revises: b7c2d1a4e9f0
Create Date: 2026-08-28 17:44:42.549449
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4c4629934230'
down_revision = 'b7c2d1a4e9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
