"""entity appearance voice evidence

Revision ID: 578eb30c44d9
Revises: b19bc1319bc6
Create Date: 2026-08-28 10:57:52.689004
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '578eb30c44d9'
down_revision = 'b19bc1319bc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world_entities', sa.Column('appearance', sa.Text(), nullable=True), schema='core')
    op.add_column('world_entities', sa.Column('voice_hints', sa.Text(), nullable=True), schema='core')
    op.add_column('world_entities', sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='core')
    op.add_column('world_entities', sa.Column('visual_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='core')
    op.add_column('world_entities', sa.Column('owner_hint', sa.String(length=128), nullable=True), schema='core')
    op.add_column('world_entities', sa.Column('usage_hint', sa.Text(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_entities', 'usage_hint', schema='core')
    op.drop_column('world_entities', 'owner_hint', schema='core')
    op.drop_column('world_entities', 'visual_keywords', schema='core')
    op.drop_column('world_entities', 'evidence_json', schema='core')
    op.drop_column('world_entities', 'voice_hints', schema='core')
    op.drop_column('world_entities', 'appearance', schema='core')
    # ### end Alembic commands ###
