"""appellation risk note

Revision ID: 5e85ee5f3af4
Revises: 01cb81a9150e
Create Date: 2026-08-28 12:25:05.833613
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5e85ee5f3af4'
down_revision = '01cb81a9150e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_appellations', sa.Column('risk_note', sa.Text(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_appellations', 'risk_note', schema='core')
    # ### end Alembic commands ###
