"""shot performance layer

Revision ID: 67c59188b3c6
Revises: b7c2d1a4e9f0
Create Date: 2026-08-28 18:08:33.958266
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '67c59188b3c6'
down_revision = 'b7c2d1a4e9f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shot_performances',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('speech_role', sa.Enum('speaker', 'addressee', 'listener', 'silent', 'absent', name='speechrole', schema='core', inherit_schema=True), nullable=False),
    sa.Column('position', sa.Enum('far_left', 'left', 'center_left', 'center', 'center_right', 'right', 'far_right', 'foreground', 'background', 'offscreen', name='stageposition', schema='core', inherit_schema=True), nullable=False),
    sa.Column('facing', sa.Enum('to_camera', 'away', 'profile_left', 'profile_right', 'three_quarter', name='facing', schema='core', inherit_schema=True), nullable=False),
    sa.Column('gaze_target', sa.String(length=128), nullable=True),
    sa.Column('expression', sa.String(length=128), nullable=True),
    sa.Column('expression_end', sa.String(length=128), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('action_end', sa.Text(), nullable=True),
    sa.Column('props_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position_jump', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_shot_performances_entity_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_shot_performances_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_performances')),
    sa.UniqueConstraint('shot_id', 'entity_id', name='uq_shot_perf_shot_entity'),
    schema='core'
    )
    op.create_index('ix_shot_perf_shot', 'shot_performances', ['shot_id', 'speech_role'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_performances_created_at'), 'shot_performances', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_performances_workspace_id'), 'shot_performances', ['workspace_id'], unique=False, schema='core')
    op.add_column('script_blocks', sa.Column('addressee_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='core')
    op.add_column('script_blocks', sa.Column('present_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_blocks', 'present_tags', schema='core')
    op.drop_column('script_blocks', 'addressee_tags', schema='core')
    op.drop_index(op.f('ix_shot_performances_workspace_id'), table_name='shot_performances', schema='core')
    op.drop_index(op.f('ix_shot_performances_created_at'), table_name='shot_performances', schema='core')
    op.drop_index('ix_shot_perf_shot', table_name='shot_performances', schema='core')
    op.drop_table('shot_performances', schema='core')
    # ### end Alembic commands ###
