"""translation block keyed by transform

Revision ID: 9480b1f8b94d
Revises: 5e85ee5f3af4
Create Date: 2026-08-28 13:02:58.298153
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9480b1f8b94d'
down_revision = '5e85ee5f3af4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先可空建列，回填后再收紧 —— 表里已有译文，直接 NOT NULL 会失败
    op.add_column('translation_blocks', sa.Column('transform_id', sa.String(length=32), nullable=True), schema='core')

    # 回填：沿 块 → 剧本 → 章节 → 小说 找到同语言的映射，active 优先。
    # 老数据是按语言存的，一个 (块, 语言) 只可能对应一版译文，所以不会撞。
    op.execute("""
        UPDATE core.translation_blocks tb
       SET transform_id = sub.tf_id
          FROM (
            SELECT tb2.id AS tb_id, wt.id AS tf_id,
                   ROW_NUMBER() OVER (
                     PARTITION BY tb2.id
                     ORDER BY (wt.status = 'active') DESC, wt.version DESC
                   ) AS rn
              FROM core.translation_blocks tb2
              JOIN core.script_blocks sb ON sb.id = tb2.script_block_id
              JOIN core.script_docs sd ON sd.id = sb.script_doc_id
              JOIN core.chapters ch ON ch.id = sd.chapter_id
              JOIN core.world_transforms wt
                ON wt.novel_id = ch.novel_id
               AND wt.target_language_code = tb2.target_language_code
          ) sub
         WHERE sub.tb_id = tb.id AND sub.rn = 1
    """)
    # 找不到对应映射的是孤儿译文（映射已删），留着会挡住 NOT NULL 且永远读不出来
    op.execute("DELETE FROM core.translation_blocks WHERE transform_id IS NULL")
    op.alter_column('translation_blocks', 'transform_id', schema='core', nullable=False)

    op.drop_constraint(op.f('uq_tb_block_lang'), 'translation_blocks', schema='core', type_='unique')
    op.create_index('ix_translation_blocks_transform', 'translation_blocks', ['transform_id', 'status'], unique=False, schema='core')
    op.create_unique_constraint('uq_tb_block_transform', 'translation_blocks', ['script_block_id', 'transform_id'], schema='core')
    op.create_foreign_key(op.f('fk_translation_blocks_transform_id'), 'translation_blocks', 'world_transforms', ['transform_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_translation_blocks_transform_id'), 'translation_blocks', schema='core', type_='foreignkey')
    op.drop_constraint('uq_tb_block_transform', 'translation_blocks', schema='core', type_='unique')
    op.drop_index('ix_translation_blocks_transform', table_name='translation_blocks', schema='core')
    op.create_unique_constraint(op.f('uq_tb_block_lang'), 'translation_blocks', ['script_block_id', 'target_language_code'], schema='core', postgresql_nulls_not_distinct=False)
    op.drop_column('translation_blocks', 'transform_id', schema='core')
    # ### end Alembic commands ###
