"""endpoint dialect

Revision ID: 99e952ab9417
Revises: ef942dd1cb5b
Create Date: 2026-08-28 12:07:46.875940
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '99e952ab9417'
down_revision = 'ef942dd1cb5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capability_endpoints', sa.Column('dialect', sa.String(length=16), nullable=False, server_default='capability'), schema='core')
    op.alter_column('capability_endpoints', 'dialect', schema='core', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capability_endpoints', 'dialect', schema='core')
    # ### end Alembic commands ###
