"""script doc mode

Revision ID: 9d8a4aa8e04d
Revises: 8850f64d7514
Create Date: 2026-08-27 18:04:50.063615
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '9d8a4aa8e04d'
down_revision = '8850f64d7514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 已有文档都是 LLM 生成的剧本，默认 screenplay 是正确的历史语义。
    # 加 NOT NULL 列到有数据的表必须给 server_default，之后再摘掉。
    # add_column 不会自己建枚举类型，先显式创建
    docmode = postgresql.ENUM('prose', 'screenplay', name='docmode', schema='core')
    docmode.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'script_docs',
        sa.Column(
            'doc_mode',
            postgresql.ENUM('prose', 'screenplay', name='docmode',
                            schema='core', create_type=False),
            nullable=False, server_default='screenplay',
        ),
        schema='core',
    )
    op.alter_column('script_docs', 'doc_mode', server_default=None, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_docs', 'doc_mode', schema='core')
    # ### end Alembic commands ###
