"""meme layer, culture review, quality tier

Revision ID: ac9c41c3ce68
Revises: 9480b1f8b94d
Create Date: 2026-08-28 17:16:34.110215
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ac9c41c3ce68'
down_revision = '9480b1f8b94d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme_entries',
    sa.Column('novel_id', sa.String(length=32), nullable=True),
    sa.Column('surface', sa.String(length=128), nullable=False),
    sa.Column('aliases_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('register', sa.Enum('internet_slang', 'subculture', 'classical_allusion', 'idiom_proverb', 'dialect', 'brand_ref', 'media_ref', 'historical_event', 'social_phenomenon', 'taboo_euphemism', name='memeregister', schema='core', inherit_schema=True), nullable=False),
    sa.Column('literal_gloss', sa.Text(), nullable=True),
    sa.Column('actual_use', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('origin_year', sa.Integer(), nullable=True),
    sa.Column('circle', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('volatility', sa.Enum('evergreen', 'decade', 'years', 'months', name='volatility', schema='core', inherit_schema=True), nullable=False),
    sa.Column('plot_load', sa.Enum('none', 'flavor', 'setup', 'pivot', name='plotload', schema='core', inherit_schema=True), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked', name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['core.novels.id'], name=op.f('fk_meme_entries_novel_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_entries')),
    sa.UniqueConstraint('novel_id', 'surface', name='uq_meme_novel_surface'),
    schema='core'
    )
    op.create_index(op.f('ix_meme_entries_created_at'), 'meme_entries', ['created_at'], unique=False, schema='core')
    op.create_index('ix_meme_entries_register', 'meme_entries', ['novel_id', 'register'], unique=False, schema='core')
    op.create_index(op.f('ix_meme_entries_workspace_id'), 'meme_entries', ['workspace_id'], unique=False, schema='core')
    op.create_table('meme_renderings',
    sa.Column('meme_id', sa.String(length=32), nullable=False),
    sa.Column('world_profile_id', sa.String(length=32), nullable=False),
    sa.Column('strategy', postgresql.ENUM('preserve', 'substitute', 'transplant', 'naturalize', 'gloss_inline', 'footnote', 'compensate', 'relocate', 'omit', name='devicestrategy', schema='core', create_type=False), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('gloss_text', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_volatility', sa.Enum('evergreen', 'decade', 'years', 'months', name='volatility', schema='core', inherit_schema=True), nullable=True),
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked', name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meme_id'], ['core.meme_entries.id'], name=op.f('fk_meme_renderings_meme_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_profile_id'], ['core.world_profiles.id'], name=op.f('fk_meme_renderings_world_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meme_renderings')),
    sa.UniqueConstraint('meme_id', 'world_profile_id', name='uq_meme_rendering_meme_profile'),
    schema='core'
    )
    op.create_index(op.f('ix_meme_renderings_created_at'), 'meme_renderings', ['created_at'], unique=False, schema='core')
    op.create_index('ix_meme_renderings_profile', 'meme_renderings', ['world_profile_id', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_meme_renderings_workspace_id'), 'meme_renderings', ['workspace_id'], unique=False, schema='core')
    op.create_table('culture_reviews',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('transform_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='reviewrunstatus', schema='core', inherit_schema=True), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False, server_default='*'),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=True),
    sa.Column('fidelity_score', sa.Integer(), nullable=True),
    sa.Column('by_kind_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings_total', sa.Integer(), nullable=False),
    sa.Column('resolved_total', sa.Integer(), nullable=False),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_culture_reviews_chapter_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transform_id'], ['core.world_transforms.id'], name=op.f('fk_culture_reviews_transform_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_culture_reviews')),
    schema='core'
    )
    op.create_index(op.f('ix_culture_reviews_created_at'), 'culture_reviews', ['created_at'], unique=False, schema='core')
    op.create_index('ix_culture_reviews_scope', 'culture_reviews', ['chapter_id', 'transform_id', 'created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_culture_reviews_workspace_id'), 'culture_reviews', ['workspace_id'], unique=False, schema='core')
    op.create_table('culture_findings',
    sa.Column('review_id', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.Enum('humor_lost', 'emotion_flattened', 'register_mismatch', 'relation_lost', 'subtext_lost', 'allusion_opaque', 'meme_untranslated', 'cultural_assumption', 'anachronism', 'taboo_shift', 'pacing_shift', 'overtranslation', name='gapkind', schema='core', inherit_schema=True), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('target_excerpt', sa.Text(), nullable=True),
    sa.Column('source_effect', sa.Text(), nullable=True),
    sa.Column('target_effect', sa.Text(), nullable=True),
    sa.Column('gap_explain', sa.Text(), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('fix_channel', sa.String(length=32), nullable=True),
    sa.Column('verdict', sa.Enum('accepted', 'modified', 'supplemented', 'rejected', 'pending', name='verdict', schema='core', inherit_schema=True), nullable=False),
    sa.Column('human_text', sa.Text(), nullable=True),
    sa.Column('human_note', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['core.culture_reviews.id'], name=op.f('fk_culture_findings_review_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_culture_findings')),
    schema='core'
    )
    op.create_index(op.f('ix_culture_findings_block_id'), 'culture_findings', ['block_id'], unique=False, schema='core')
    op.create_index(op.f('ix_culture_findings_created_at'), 'culture_findings', ['created_at'], unique=False, schema='core')
    op.create_index('ix_culture_findings_review', 'culture_findings', ['review_id', 'severity'], unique=False, schema='core')
    op.create_index('ix_culture_findings_verdict', 'culture_findings', ['review_id', 'verdict'], unique=False, schema='core')
    op.create_index(op.f('ix_culture_findings_workspace_id'), 'culture_findings', ['workspace_id'], unique=False, schema='core')
    op.add_column('capability_routes', sa.Column('tier', sa.String(length=16), nullable=False, server_default='*'), schema='core')
    op.alter_column('capability_routes', 'tier', schema='core', server_default=None)
    op.drop_constraint(op.f('uq_capability_routes_cap_purpose_prio'), 'capability_routes', schema='core', type_='unique')
    op.drop_index(op.f('ix_capability_routes_lookup'), table_name='capability_routes', schema='core')
    op.create_index('ix_capability_routes_lookup', 'capability_routes', ['capability', 'purpose', 'tier', 'enabled'], unique=False, schema='core')
    op.create_unique_constraint('uq_capability_routes_cap_purpose_tier_prio', 'capability_routes', ['capability', 'purpose', 'tier', 'priority'], schema='core')
    op.add_column('narrative_devices', sa.Column('plot_load', sa.Enum('none', 'flavor', 'setup', 'pivot', name='plotload', schema='core', inherit_schema=True), nullable=False), schema='core')
    op.add_column('narrative_devices', sa.Column('volatility', sa.Enum('evergreen', 'decade', 'years', 'months', name='volatility', schema='core', inherit_schema=True), nullable=False), schema='core')
    op.add_column('narrative_devices', sa.Column('gloss_text', sa.Text(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narrative_devices', 'gloss_text', schema='core')
    op.drop_column('narrative_devices', 'volatility', schema='core')
    op.drop_column('narrative_devices', 'plot_load', schema='core')
    op.drop_constraint('uq_capability_routes_cap_purpose_tier_prio', 'capability_routes', schema='core', type_='unique')
    op.drop_index('ix_capability_routes_lookup', table_name='capability_routes', schema='core')
    op.create_index(op.f('ix_capability_routes_lookup'), 'capability_routes', ['capability', 'purpose', 'enabled'], unique=False, schema='core')
    op.create_unique_constraint(op.f('uq_capability_routes_cap_purpose_prio'), 'capability_routes', ['capability', 'purpose', 'priority'], schema='core', postgresql_nulls_not_distinct=False)
    op.drop_column('capability_routes', 'tier', schema='core')
    op.drop_index(op.f('ix_culture_findings_workspace_id'), table_name='culture_findings', schema='core')
    op.drop_index('ix_culture_findings_verdict', table_name='culture_findings', schema='core')
    op.drop_index('ix_culture_findings_review', table_name='culture_findings', schema='core')
    op.drop_index(op.f('ix_culture_findings_created_at'), table_name='culture_findings', schema='core')
    op.drop_index(op.f('ix_culture_findings_block_id'), table_name='culture_findings', schema='core')
    op.drop_table('culture_findings', schema='core')
    op.drop_index(op.f('ix_culture_reviews_workspace_id'), table_name='culture_reviews', schema='core')
    op.drop_index('ix_culture_reviews_scope', table_name='culture_reviews', schema='core')
    op.drop_index(op.f('ix_culture_reviews_created_at'), table_name='culture_reviews', schema='core')
    op.drop_table('culture_reviews', schema='core')
    op.drop_index(op.f('ix_meme_renderings_workspace_id'), table_name='meme_renderings', schema='core')
    op.drop_index('ix_meme_renderings_profile', table_name='meme_renderings', schema='core')
    op.drop_index(op.f('ix_meme_renderings_created_at'), table_name='meme_renderings', schema='core')
    op.drop_table('meme_renderings', schema='core')
    op.drop_index(op.f('ix_meme_entries_workspace_id'), table_name='meme_entries', schema='core')
    op.drop_index('ix_meme_entries_register', table_name='meme_entries', schema='core')
    op.drop_index(op.f('ix_meme_entries_created_at'), table_name='meme_entries', schema='core')
    op.drop_table('meme_entries', schema='core')
    # ### end Alembic commands ###
