"""entity name type

Revision ID: adb57477f55b
Revises: 4a73d0dc50ee
Create Date: 2026-08-29 00:21:48.931508
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'adb57477f55b'
down_revision = '4a73d0dc50ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 新枚举必须显式 CREATE TYPE —— add_column 里的 sa.Enum 只负责
    # 在列上引用这个类型，不负责建它，于是报 type "core.nametype" does not exist。
    nametype = postgresql.ENUM(
        'proper', 'role', 'epithet', 'generic',
        name='nametype', schema='core', create_type=False,
    )
    nametype.create(op.get_bind(), checkfirst=True)
    op.add_column('world_entities', sa.Column('name_type', sa.Enum('proper', 'role', 'epithet', 'generic', name='nametype', schema='core', inherit_schema=True), nullable=False, server_default='proper'), schema='core')
    # 已有实体一律先当 proper —— 那是原来的隐含假设。
    # 重跑抽取时模型会给出真实判断并覆盖它（见 entities.py 的补空逻辑）。
    op.alter_column('world_entities', 'name_type', schema='core', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world_entities', 'name_type', schema='core')
    op.execute('DROP TYPE IF EXISTS core.nametype')
    # ### end Alembic commands ###
