"""world model extraction fields beats style hints

Revision ID: b19bc1319bc6
Revises: 9d8a4aa8e04d
Create Date: 2026-08-28 10:55:43.461428
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b19bc1319bc6'
down_revision = '9d8a4aa8e04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_beats',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tension_level', sa.Integer(), nullable=False),
    sa.Column('location_text', sa.String(length=256), nullable=True),
    sa.Column('entity_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scene_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_story_beats_chapter_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_beats')),
    sa.UniqueConstraint('chapter_id', 'order_no', name='uq_story_beats_chapter_order'),
    schema='core'
    )
    op.create_index('ix_story_beats_chapter', 'story_beats', ['chapter_id'], unique=False, schema='core')
    op.create_index(op.f('ix_story_beats_created_at'), 'story_beats', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_story_beats_workspace_id'), 'story_beats', ['workspace_id'], unique=False, schema='core')
    op.create_table('style_hints',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('lighting_style', sa.Text(), nullable=True),
    sa.Column('color_palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mood', sa.String(length=128), nullable=True),
    sa.Column('camera_hint', sa.Text(), nullable=True),
    sa.Column('texture', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_style_hints_chapter_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_hints')),
    schema='core'
    )
    op.create_index('ix_style_hints_chapter', 'style_hints', ['chapter_id'], unique=False, schema='core')
    op.create_index(op.f('ix_style_hints_created_at'), 'style_hints', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_style_hints_workspace_id'), 'style_hints', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_hints_workspace_id'), table_name='style_hints', schema='core')
    op.drop_index(op.f('ix_style_hints_created_at'), table_name='style_hints', schema='core')
    op.drop_index('ix_style_hints_chapter', table_name='style_hints', schema='core')
    op.drop_table('style_hints', schema='core')
    op.drop_index(op.f('ix_story_beats_workspace_id'), table_name='story_beats', schema='core')
    op.drop_index(op.f('ix_story_beats_created_at'), table_name='story_beats', schema='core')
    op.drop_index('ix_story_beats_chapter', table_name='story_beats', schema='core')
    op.drop_table('story_beats', schema='core')
    # ### end Alembic commands ###
