"""crew sheets

Revision ID: de6fc0de7c7d
Revises: e68840dff2ff
Create Date: 2026-08-29 07:43:27.213456
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'de6fc0de7c7d'
down_revision = 'e68840dff2ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_castings',
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('world_profile_id', sa.String(length=32), nullable=False),
    sa.Column('epoch_key', sa.String(length=64), nullable=False),
    sa.Column('timbre_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice_ref', sa.String(length=128), nullable=True),
    sa.Column('voice_asset_id', sa.String(length=32), nullable=True),
    sa.Column('speech_habits', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked', name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['core.world_entities.id'], name=op.f('fk_voice_castings_entity_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_profile_id'], ['core.world_profiles.id'], name=op.f('fk_voice_castings_world_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_castings')),
    sa.UniqueConstraint('entity_id', 'world_profile_id', 'epoch_key', name='uq_voice_casting_entity_profile_epoch'),
    schema='core'
    )
    op.create_index(op.f('ix_voice_castings_created_at'), 'voice_castings', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_voice_castings_workspace_id'), 'voice_castings', ['workspace_id'], unique=False, schema='core')
    sheetstatus = postgresql.ENUM(
        'pending', 'drafted', 'reviewed', 'locked',
        name='sheetstatus', schema='core', create_type=False,
    )
    sheetstatus.create(op.get_bind(), checkfirst=True)
    op.create_table('crew_sheets',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('missing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'drafted', 'reviewed', 'locked', name='sheetstatus', schema='core', create_type=False), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_crew_sheets_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_sheets')),
    sa.UniqueConstraint('shot_id', 'role', name='uq_crew_sheet_shot_role'),
    schema='core'
    )
    op.create_index('ix_crew_sheet_role', 'crew_sheets', ['role', 'status'], unique=False, schema='core')
    op.create_index(op.f('ix_crew_sheets_created_at'), 'crew_sheets', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_crew_sheets_workspace_id'), 'crew_sheets', ['workspace_id'], unique=False, schema='core')
    op.create_table('shot_motions',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('start_frame', sa.Text(), nullable=True),
    sa.Column('end_frame', sa.Text(), nullable=True),
    sa.Column('camera_move', sa.Text(), nullable=True),
    sa.Column('subject_move', sa.Text(), nullable=True),
    sa.Column('pacing', sa.String(length=128), nullable=True),
    sa.Column('deltas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motion_prompt', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'drafted', 'reviewed', 'locked', name='sheetstatus', schema='core', create_type=False), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_shot_motions_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_motions')),
    sa.UniqueConstraint('shot_id', name='uq_shot_motion_shot'),
    schema='core'
    )
    op.create_index(op.f('ix_shot_motions_created_at'), 'shot_motions', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_shot_motions_workspace_id'), 'shot_motions', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_motions_workspace_id'), table_name='shot_motions', schema='core')
    op.drop_index(op.f('ix_shot_motions_created_at'), table_name='shot_motions', schema='core')
    op.drop_table('shot_motions', schema='core')
    op.drop_index(op.f('ix_crew_sheets_workspace_id'), table_name='crew_sheets', schema='core')
    op.drop_index(op.f('ix_crew_sheets_created_at'), table_name='crew_sheets', schema='core')
    op.drop_index('ix_crew_sheet_role', table_name='crew_sheets', schema='core')
    op.drop_table('crew_sheets', schema='core')
    op.drop_index(op.f('ix_voice_castings_workspace_id'), table_name='voice_castings', schema='core')
    op.drop_index(op.f('ix_voice_castings_created_at'), table_name='voice_castings', schema='core')
    op.drop_table('voice_castings', schema='core')
    # ### end Alembic commands ###
