"""asset epochs

Revision ID: e68840dff2ff
Revises: adb57477f55b
Create Date: 2026-08-29 07:22:47.965027
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e68840dff2ff'
down_revision = 'adb57477f55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    epochkind = postgresql.ENUM(
        'baseline', 'age', 'status', 'gear', 'injury', 'season', 'ruin', 'disguise',
        name='epochkind', schema='core', create_type=False,
    )
    epochkind.create(op.get_bind(), checkfirst=True)
    op.create_table('asset_epochs',
    sa.Column('asset_spec_id', sa.String(length=32), nullable=False),
    sa.Column('world_profile_id', sa.String(length=32), nullable=False),
    sa.Column('epoch_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('kind', postgresql.ENUM('baseline', 'age', 'status', 'gear', 'injury', 'season', 'ruin', 'disguise', name='epochkind', schema='core', create_type=False), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('from_chapter_order', sa.Integer(), nullable=False),
    sa.Column('to_chapter_order', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('trigger_chapter_id', sa.String(length=32), nullable=True),
    sa.Column('invariant_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identity_ref_asset_id', sa.String(length=32), nullable=True),
    sa.Column('status', postgresql.ENUM('candidate', 'approved', 'locked', name='reviewstatus', schema='core', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_spec_id'], ['core.asset_specs.id'], name=op.f('fk_asset_epochs_asset_spec_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_profile_id'], ['core.world_profiles.id'], name=op.f('fk_asset_epochs_world_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_epochs')),
    sa.UniqueConstraint('asset_spec_id', 'world_profile_id', 'epoch_key', name='uq_asset_epoch_spec_profile_key'),
    schema='core'
    )
    op.create_index('ix_asset_epoch_lookup', 'asset_epochs', ['asset_spec_id', 'world_profile_id', 'from_chapter_order'], unique=False, schema='core')
    op.create_index(op.f('ix_asset_epochs_created_at'), 'asset_epochs', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_asset_epochs_workspace_id'), 'asset_epochs', ['workspace_id'], unique=False, schema='core')
    op.create_table('epoch_bindings',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('asset_spec_id', sa.String(length=32), nullable=False),
    sa.Column('asset_epoch_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_by', sa.String(length=16), nullable=False),
    sa.Column('reused_from_shot_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_epoch_id'], ['core.asset_epochs.id'], name=op.f('fk_epoch_bindings_asset_epoch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_spec_id'], ['core.asset_specs.id'], name=op.f('fk_epoch_bindings_asset_spec_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['core.shots.id'], name=op.f('fk_epoch_bindings_shot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_epoch_bindings')),
    sa.UniqueConstraint('shot_id', 'asset_spec_id', name='uq_epoch_binding_shot_spec'),
    schema='core'
    )
    op.create_index('ix_epoch_binding_epoch', 'epoch_bindings', ['asset_epoch_id'], unique=False, schema='core')
    op.create_index(op.f('ix_epoch_bindings_created_at'), 'epoch_bindings', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_epoch_bindings_workspace_id'), 'epoch_bindings', ['workspace_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epoch_bindings_workspace_id'), table_name='epoch_bindings', schema='core')
    op.drop_index(op.f('ix_epoch_bindings_created_at'), table_name='epoch_bindings', schema='core')
    op.drop_index('ix_epoch_binding_epoch', table_name='epoch_bindings', schema='core')
    op.drop_table('epoch_bindings', schema='core')
    op.drop_index(op.f('ix_asset_epochs_workspace_id'), table_name='asset_epochs', schema='core')
    op.drop_index(op.f('ix_asset_epochs_created_at'), table_name='asset_epochs', schema='core')
    op.drop_index('ix_asset_epoch_lookup', table_name='asset_epochs', schema='core')
    op.drop_table('asset_epochs', schema='core')
    # ### end Alembic commands ###
