"""narrative devices and back translation

Revision ID: ef942dd1cb5b
Revises: 578eb30c44d9
Create Date: 2026-08-28 11:21:49.702814
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ef942dd1cb5b'
down_revision = '578eb30c44d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('back_translation_checks',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('transform_id', sa.String(length=32), nullable=True),
    sa.Column('target_language_code', sa.String(length=16), nullable=False),
    sa.Column('beat_coverage', sa.Float(), nullable=False),
    sa.Column('device_landing', sa.Float(), nullable=False),
    sa.Column('emotion_match', sa.Float(), nullable=False),
    sa.Column('missing_beats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lost_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_back_translation_checks_chapter_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_back_translation_checks')),
    schema='core'
    )
    op.create_index(op.f('ix_back_translation_checks_created_at'), 'back_translation_checks', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_back_translation_checks_workspace_id'), 'back_translation_checks', ['workspace_id'], unique=False, schema='core')
    op.create_index('ix_bt_checks_chapter', 'back_translation_checks', ['chapter_id', 'target_language_code'], unique=False, schema='core')
    op.create_table('narrative_devices',
    sa.Column('chapter_id', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=True),
    sa.Column('beat_id', sa.String(length=32), nullable=True),
    sa.Column('device_type', sa.Enum('pun', 'wordplay', 'misdirection', 'exaggeration', 'understatement', 'irony', 'callback', 'cultural_ref', 'idiom', 'register_shift', 'repetition', 'juxtaposition', 'dramatic_irony', 'foreshadow', 'sensory', name='devicetype', schema='core', inherit_schema=True), nullable=False),
    sa.Column('effect', sa.Enum('humor', 'tension', 'warmth', 'grief', 'awe', 'dread', 'relief', 'irony', 'intimacy', 'contempt', name='deviceeffect', schema='core', inherit_schema=True), nullable=False),
    sa.Column('cultural_load', sa.Enum('low', 'medium', 'high', name='culturalload', schema='core', inherit_schema=True), nullable=False),
    sa.Column('strategy', sa.Enum('preserve', 'substitute', 'compensate', 'relocate', 'drop', name='devicestrategy', schema='core', inherit_schema=True), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('setup', sa.Text(), nullable=True),
    sa.Column('punch', sa.Text(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_plan', sa.Text(), nullable=True),
    sa.Column('landed', sa.Boolean(), nullable=True),
    sa.Column('landed_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['core.chapters.id'], name=op.f('fk_narrative_devices_chapter_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narrative_devices')),
    schema='core'
    )
    op.create_index('ix_narrative_devices_block', 'narrative_devices', ['block_id'], unique=False, schema='core')
    op.create_index('ix_narrative_devices_chapter', 'narrative_devices', ['chapter_id'], unique=False, schema='core')
    op.create_index(op.f('ix_narrative_devices_created_at'), 'narrative_devices', ['created_at'], unique=False, schema='core')
    op.create_index('ix_narrative_devices_load', 'narrative_devices', ['cultural_load'], unique=False, schema='core')
    op.create_index(op.f('ix_narrative_devices_workspace_id'), 'narrative_devices', ['workspace_id'], unique=False, schema='core')
    op.add_column('story_beats', sa.Column('beat_type', sa.String(length=24), nullable=True), schema='core')
    op.add_column('story_beats', sa.Column('emotion', sa.String(length=32), nullable=True), schema='core')
    # 已有节拍没有情绪强度，给默认值 3（中性）后再摘掉 server_default
    op.add_column(
        'story_beats',
        sa.Column('emotion_intensity', sa.Integer(), nullable=False,
                  server_default='3'),
        schema='core',
    )
    op.alter_column('story_beats', 'emotion_intensity',
                    server_default=None, schema='core')
    op.add_column('story_beats', sa.Column('plot_point', sa.Text(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_beats', 'plot_point', schema='core')
    op.drop_column('story_beats', 'emotion_intensity', schema='core')
    op.drop_column('story_beats', 'emotion', schema='core')
    op.drop_column('story_beats', 'beat_type', schema='core')
    op.drop_index(op.f('ix_narrative_devices_workspace_id'), table_name='narrative_devices', schema='core')
    op.drop_index('ix_narrative_devices_load', table_name='narrative_devices', schema='core')
    op.drop_index(op.f('ix_narrative_devices_created_at'), table_name='narrative_devices', schema='core')
    op.drop_index('ix_narrative_devices_chapter', table_name='narrative_devices', schema='core')
    op.drop_index('ix_narrative_devices_block', table_name='narrative_devices', schema='core')
    op.drop_table('narrative_devices', schema='core')
    op.drop_index('ix_bt_checks_chapter', table_name='back_translation_checks', schema='core')
    op.drop_index(op.f('ix_back_translation_checks_workspace_id'), table_name='back_translation_checks', schema='core')
    op.drop_index(op.f('ix_back_translation_checks_created_at'), table_name='back_translation_checks', schema='core')
    op.drop_table('back_translation_checks', schema='core')
    # ### end Alembic commands ###
